import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
const s=createClient('https://qgakliolffnwkymoqvzn.supabase.co','sb_publishable_WbZxATu_lxqWF21jR_qFag_fcEeVIMu');
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v||0));
const phoneKey=v=>String(v||'').replace(/\D/g,'');
const parseDate=v=>{const[a,b,c]=String(v).split('-').map(Number);return new Date(a,b-1,c)};
let user=null,profiles=[],profile=null,scopeProfiles=[],bookings=[],services=[],serviceMap=new Map(),notes=[],clients=[],selectedKey=null;
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function statusLabel(v){return({BOOKED:'Ожидается',ARRIVED:'Пришёл',DONE:'Выполнено',CANCELLED:'Отменено',NO_SHOW:'Не пришёл'})[v]||v}
async function loadProfiles(){const{data,error}=await s.from('marketplace_beauty_profiles').select('id,display_name,salon_id,owner_auth_user_id,is_active').eq('is_active',true).order('display_name');if(error)throw error;profiles=data||[];if(!profiles.length){location.href='/beauty-register.html';return}const p=new URLSearchParams(location.search),wanted=p.get('profile');profile=profiles.find(x=>x.id===wanted)||profiles[0];$('profileSelect').innerHTML=profiles.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('');$('profileSelect').value=profile.id}
function makeScope(){scopeProfiles=profile.salon_id?profiles.filter(x=>x.salon_id===profile.salon_id):[profile];$('scopeTitle').textContent=profile.salon_id?`Клиенты салона · ${scopeProfiles.length} мастеров`:`Клиенты мастера ${profile.display_name}`}
async function loadData(){makeScope();const ids=scopeProfiles.map(x=>x.id);const[{data:sv,error:se},{data:bk,error:be},{data:nt,error:ne}]=await Promise.all([s.from('marketplace_beauty_services').select('id,profile_id,title,price,duration_minutes').in('profile_id',ids),s.from('marketplace_beauty_bookings').select('id,profile_id,service_id,customer_name,customer_phone,comment,booking_date,start_time,end_time,status,booking_source,created_at').in('profile_id',ids).order('booking_date',{ascending:false}).order('start_time',{ascending:false}).limit(2000),s.from('marketplace_beauty_client_notes').select('id,customer_phone,customer_phone_key,customer_name,notes,tags,updated_at').eq('owner_auth_user_id',user.id)]);if(se)throw se;if(be)throw be;if(ne)throw ne;services=sv||[];serviceMap=new Map(services.map(x=>[x.id,x]));bookings=bk||[];notes=nt||[];buildClients();renderList();renderStats();const queryPhone=new URLSearchParams(location.search).get('phone');if(queryPhone){const k=phoneKey(queryPhone);if(clients.some(x=>x.key===k))selectClient(k)}else if(selectedKey&&clients.some(x=>x.key===selectedKey))selectClient(selectedKey)}
function buildClients(){const noteMap=new Map(notes.map(x=>[x.customer_phone_key,x])),m=new Map;for(const b of bookings){const key=phoneKey(b.customer_phone);if(!key)continue;let c=m.get(key);if(!c){c={key,name:b.customer_name,phone:b.customer_phone,bookings:[],done:0,cancelled:0,noShow:0,revenue:0,last:null,next:null,note:noteMap.get(key)||null};m.set(key,c)}c.bookings.push(b);if(b.status==='DONE'){c.done++;c.revenue+=Number(serviceMap.get(b.service_id)?.price||0);if(!c.last||`${b.booking_date} ${b.start_time}`>`${c.last.booking_date} ${c.last.start_time}`)c.last=b}if(b.status==='CANCELLED')c.cancelled++;if(b.status==='NO_SHOW')c.noShow++;if(['BOOKED','ARRIVED'].includes(b.status)&&`${b.booking_date} ${b.start_time}`>=new Date().toISOString().slice(0,10)){if(!c.next||`${b.booking_date} ${b.start_time}`<`${c.next.booking_date} ${c.next.start_time}`)c.next=b}if(`${b.booking_date} ${b.start_time}`>${c._latest||''}){c._latest=`${b.booking_date} ${b.start_time}`;c.name=b.customer_name;c.phone=b.customer_phone}}clients=[...m.values()].sort((a,b)=>(b._latest||'').localeCompare(a._latest||''))}
function renderStats(){$('statClients').textContent=clients.length;$('statDone').textContent=clients.reduce((n,c)=>n+c.done,0);$('statRepeat').textContent=clients.filter(c=>c.done>=2).length;$('statRevenue').textContent=money(clients.reduce((n,c)=>n+c.revenue,0))}
function renderList(){const q=$('clientSearch').value.trim().toLowerCase();const a=clients.filter(c=>!q||`${c.name} ${c.phone}`.toLowerCase().includes(q));$('clientList').innerHTML=a.length?a.map(c=>`<article class="client ${c.key===selectedKey?'active':''}" data-client="${c.key}"><div class="client-top"><div><b>${esc(c.name)}</b><small>${esc(c.phone)}</small></div>${c.next?'<span class="pill green">есть запись</span>':''}</div><div class="client-kpis"><span class="pill">${c.done} визитов</span>${c.revenue?`<span class="pill">${money(c.revenue)}</span>`:''}${c.noShow?`<span class="pill red">неявок ${c.noShow}</span>`:''}${c.note?.tags?.slice(0,2).map(t=>`<span class="pill">${esc(t)}</span>`).join('')||''}</div></article>`).join(''):'<div class="empty">Поиск не дал результатов.</div>';document.querySelectorAll('[data-client]').forEach(el=>el.onclick=()=>selectClient(el.dataset.client))}
function selectClient(key){selectedKey=key;renderList();const c=clients.find(x=>x.key===key);if(!c)return;const history=[...c.bookings].sort((a,b)=>`${b.booking_date} ${b.start_time}`.localeCompare(`${a.booking_date} ${a.start_time}`));const lastService=history.find(x=>x.status==='DONE')||history[0],prof=profiles.find(x=>x.id===lastService?.profile_id)||profile,svc=serviceMap.get(lastService?.service_id);$('clientDetail').innerHTML=`<div class="section-title"><div><h2>${esc(c.name)}</h2><div class="crm-contact">${esc(c.phone)} · ${c.next?'следующая запись '+parseDate(c.next.booking_date).toLocaleDateString('ru-RU')+' в '+String(c.next.start_time).slice(0,5):'нет будущей записи'}</div></div><a class="btn" href="/beauty-calendar.html?new=1&profile=${encodeURIComponent(prof.id)}&name=${encodeURIComponent(c.name)}&phone=${encodeURIComponent(c.phone)}${svc?`&service=${encodeURIComponent(svc.id)}`:''}">Записать снова</a></div><div class="crm-kpis"><div class="mini"><small>Завершено</small><b>${c.done}</b></div><div class="mini"><small>Выручка</small><b>${money(c.revenue)}</b></div><div class="mini"><small>Отменено</small><b>${c.cancelled}</b></div><div class="mini"><small>Неявки</small><b>${c.noShow}</b></div></div><div class="form-two"><div class="field"><label>Заметки о клиенте</label><textarea id="clientNotes" rows="4" placeholder="Предпочтения, формула окрашивания, аллергии, важные детали">${esc(c.note?.notes||'')}</textarea></div><div class="field"><label>Теги через запятую</label><textarea id="clientTags" rows="4" placeholder="VIP, блонд, маникюр, постоянный">${esc((c.note?.tags||[]).join(', '))}</textarea></div></div><button class="btn light small" id="saveNote" style="margin-top:8px">Сохранить заметки</button><div class="section-title" style="margin-top:18px"><div><h2>История посещений</h2><p>${history.length} записей в ЦУИМ</p></div></div><div class="history">${history.map(b=>{const s1=serviceMap.get(b.service_id)||{},p1=profiles.find(x=>x.id===b.profile_id);return`<div class="history-row"><div><b>${parseDate(b.booking_date).toLocaleDateString('ru-RU')} · ${String(b.start_time).slice(0,5)} · ${esc(s1.title||'Услуга')}</b><small>${esc(p1?.display_name||'Мастер')} · ${money(s1.price)} · ${b.booking_source==='MANUAL'?'ручная запись':'онлайн'}${b.comment?'<br>'+esc(b.comment):''}</small></div><span class="pill ${b.status==='DONE'?'green':b.status==='NO_SHOW'||b.status==='CANCELLED'?'red':''}">${statusLabel(b.status)}</span></div>`}).join('')}</div>`;$('saveNote').onclick=()=>saveNote(c)}
async function saveNote(c){const tags=$('clientTags').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);const row={owner_auth_user_id:user.id,customer_phone:c.phone,customer_name:c.name,notes:$('clientNotes').value.trim()||null,tags,updated_at:new Date().toISOString()};const{error}=await s.from('marketplace_beauty_client_notes').upsert(row,{onConflict:'owner_auth_user_id,customer_phone_key'});if(error){toast(error.message);return}toast('Заметки сохранены');await loadData()}
$('clientSearch').oninput=renderList;$('profileSelect').onchange=async()=>{profile=profiles.find(x=>x.id===$('profileSelect').value);selectedKey=null;await loadData()};
async function init(){const{data:{user:u},error}=await s.auth.getUser();if(error||!u){location.href='/login.html?next=/beauty-clients.html';return}user=u;try{await loadProfiles();await loadData()}catch(e){toast(e.message||'Ошибка загрузки')}}
init();