import'/geo-core.js';
import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
const s=createClient('https://qgakliolffnwkymoqvzn.supabase.co','sb_publishable_WbZxATu_lxqWF21jR_qFag_fcEeVIMu');
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const svg=(body,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons={
 ALL:svg('<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>'),
 NAILS:svg('<path d="M9 4h6l1 4v11a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V8l1-4Z"/><path d="M9 8h6M10 13h4M11 4V2h2v2"/>'),
 HAIR:svg('<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="m8.5 7.5 11 7M8.5 16.5l11-7"/>'),
 BROWS:svg('<path d="M3 12s3-5 9-5 9 5 9 5-3 5-9 5-9-5-9-5Z"/><circle cx="12" cy="12" r="2.4"/><path d="M5 7.5 8 5m1 1-1-3m3 2V2m2 3 1-3m1 4 3-2"/>'),
 LASHES:svg('<path d="M3 13s3-4 9-4 9 4 9 4-3 4-9 4-9-4-9-4Z"/><path d="M6 9 5 6m4 2V5m3 3V4m3 4V5m3 4 1-3"/>'),
 MAKEUP:svg('<path d="m5 19 9-9 4 4-9 9H5v-4Z"/><path d="m14 10 2-6 4 4-6 2Z"/><path d="M5 19h4v4"/>'),
 COSMETOLOGY:svg('<path d="M12 3c4 0 7 3.2 7 7.3 0 5.1-3.1 9.7-7 10.7-3.9-1-7-5.6-7-10.7C5 6.2 8 3 12 3Z"/><path d="M8.8 11h.1m6.2 0h.1M9.5 15c1.5 1 3.5 1 5 0"/><path d="m3 5 1-1m16 1 1-1"/>'),
 MASSAGE:svg('<path d="M4 16c2-5 5-7 8-7 2.5 0 4.4 1.4 5.5 3.2L20 16"/><path d="M3 19c3-2 6-3 9-3s6 1 9 3M8 9l1-4m6 4-1-4"/>'),
 BARBER:svg('<rect x="8" y="3" width="8" height="18" rx="3"/><path d="m8 8 8-4M8 14l8-4m-8 10 8-4"/>'),
 DEPILATION:svg('<path d="M12 3c3 4 5 6.5 5 10a5 5 0 0 1-10 0c0-3.5 2-6 5-10Z"/><path d="M9.5 14.5c.5 1.2 1.3 1.8 2.5 2"/>'),
 OTHER:svg('<circle cx="12" cy="12" r="9"/><path d="M12 8v8M8 12h8"/>'),
 search:svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'),
 pin:svg('<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>'),
 salon:svg('<path d="M4 21V7l8-4 8 4v14M8 21v-5h8v5M8 10h.01M12 10h.01M16 10h.01"/>'),
 clock:svg('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),
 calendar:svg('<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 10h18"/>'),
 star:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2.8 2.8 5.7 6.3.9-4.6 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2-4.6-4.4 6.3-.9L12 2.8Z"/></svg>`,
 arrow:svg('<path d="M5 12h14m-5-5 5 5-5 5"/>')
};
const specs={ALL:{title:'Все направления',short:'Все',desc:'Все специалисты'},NAILS:{title:'Ногти',short:'Ногти',desc:'Маникюр и педикюр'},HAIR:{title:'Парикмахеры',short:'Волосы',desc:'Стрижки и окрашивание'},BROWS:{title:'Брови',short:'Брови',desc:'Форма и окрашивание'},LASHES:{title:'Ресницы',short:'Ресницы',desc:'Ламинирование и наращивание'},MAKEUP:{title:'Макияж',short:'Макияж',desc:'Дневной и вечерний'},COSMETOLOGY:{title:'Косметология',short:'Косметология',desc:'Уход за лицом'},MASSAGE:{title:'Массаж',short:'Массаж',desc:'Массаж и SPA'},BARBER:{title:'Барберы',short:'Барберы',desc:'Мужские стрижки'},DEPILATION:{title:'Депиляция',short:'Депиляция',desc:'Гладкость и уход'},OTHER:{title:'Другие услуги',short:'Другое',desc:'Другие специалисты'}};
let current='ALL',allRows=[],geoContext=window.CUIM_GEO?.get?.()||null;
function money(v){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v||0))}
function initials(v){return String(v||'М').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function radiusKm(){return Math.max(1,Math.round(Number(geoContext?.radius_m||3000)/1000))}
function geoLabel(){if(!geoContext?.city_name)return'Москва';if(geoContext.metro_name)return`${geoContext.city_name} · м. ${geoContext.metro_name} · ${radiusKm()} км`;return geoContext.area_name?`${geoContext.city_name} · ${geoContext.area_short_name||geoContext.area_name}`:geoContext.city_name}
function refreshGeoSelect(){geoContext=window.CUIM_GEO?.get?.()||geoContext;const c=$('city');if(!c)return;c.innerHTML=`<option value="">${esc(geoLabel())}</option><option value="__choose__">Изменить район / метро…</option>`;c.value=''}
function renderSpecialties(){const keys=Object.keys(specs);$('specialtyGrid').innerHTML=keys.map(k=>`<button class="specialty ${k===current?'active':''}" data-spec="${k}"><span class="specialty-icon">${icons[k]}</span><span><b>${esc(specs[k].title)}</b><small>${esc(specs[k].desc)}</small></span></button>`).join('');$('specialtySelect').innerHTML=keys.map(k=>`<option value="${k}">${esc(specs[k].title)}</option>`).join('');$('specialtySelect').value=current}
function applyClientFilters(){let a=[...allRows];const max=Number($('maxPrice').value||0),minRating=Number($('minRating').value||0);if(max>0)a=a.filter(x=>x.starting_price==null||Number(x.starting_price)<=max);if(minRating>0)a=a.filter(x=>Number(x.rating||0)>=minRating);const sort=$('sort').value;if(sort==='rating')a.sort((x,y)=>Number(y.rating||0)-Number(x.rating||0));else if(sort==='price')a.sort((x,y)=>(x.starting_price==null?1e15:Number(x.starting_price))-(y.starting_price==null?1e15:Number(y.starting_price)));else if(sort==='reviews')a.sort((x,y)=>Number(y.review_count||0)-Number(x.review_count||0));renderMasters(a)}
function metroDistance(x){if(!geoContext?.metro_name||!Number.isFinite(Number(x.metro_distance_m)))return'';const m=Number(x.metro_distance_m),km=Math.max(.1,m/1000);return`${km.toFixed(m<1000?1:0)} км от м. ${geoContext.metro_name}`}
function renderMasters(a){$('count').textContent=`${a.length} ${a.length===1?'специалист':'специалистов'} · ${geoLabel()}`;if(!a.length){$('list').innerHTML=`<div class="empty"><div class="empty-icon">${icons.search}</div><div><b>В выбранной локации пока никого не нашли</b><p>${esc(geoLabel())}. Попробуйте увеличить радиус, выбрать другое метро или соседний район. Если вы мастер или салон, можно стать первым специалистом здесь.</p></div><a class="btn" href="/beauty-register.html">Разместить профиль</a></div>`;return}$('list').innerHTML=a.map(x=>`<article class="master"><a class="master-main" href="/beauty-master.html?id=${encodeURIComponent(x.id)}"><div class="avatar">${x.avatar_url?`<img src="${esc(x.avatar_url)}" alt="${esc(x.display_name)}">`:`<span>${esc(initials(x.display_name))}</span>`}</div><div class="master-copy"><div class="master-topline"><div><h3>${esc(x.display_name)}</h3><div class="spec">${esc(specs[x.specialty]?.title||'Мастер красоты')}</div></div>${x.rating?`<span class="rating">${icons.star}${esc(x.rating)}</span>`:''}</div><div class="headline">${esc(x.headline||x.bio||'Специалист красоты с онлайн-записью в ЦУИМ')}</div></div></a><div class="facts">${x.city?`<span class="fact">${icons.pin}${esc(x.city)}</span>`:''}${metroDistance(x)?`<span class="fact">${icons.pin}${esc(metroDistance(x))}</span>`:''}${x.salon_name?`<span class="fact">${icons.salon}${esc(x.salon_name)}</span>`:''}${x.experience_years!=null?`<span class="fact">${icons.clock}Опыт ${Number(x.experience_years)} г.</span>`:''}<span class="fact">${icons.calendar}${Number(x.service_count||0)} услуг</span>${x.review_count?`<span class="fact">${Number(x.review_count)} отзывов</span>`:''}</div><div class="master-footer"><div class="price"><small>Стоимость</small>${x.starting_price!=null?'от '+money(x.starting_price):'Смотреть цены'}</div><a class="book" href="/beauty-master.html?id=${encodeURIComponent(x.id)}">Выбрать время ${icons.arrow}</a></div></article>`).join('')}
async function load(){await window.CUIM_GEO?.ready?.catch?.(()=>{});geoContext=window.CUIM_GEO?.get?.()||geoContext;refreshGeoSelect();const list=$('list');list.innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';const{data,error}=await s.rpc('marketplace_beauty_directory_v3',{p_query:$('q').value.trim()||null,p_specialty:current==='ALL'?null:current,p_city_id:geoContext?.city_id||null,p_area_id:geoContext?.area_id||null,p_metro_id:geoContext?.metro_id||null,p_radius_m:Number(geoContext?.radius_m||3000)});if(error){list.innerHTML=`<div class="empty"><div class="empty-icon">${icons.search}</div><div><b>Не удалось загрузить мастеров</b><p>${esc(error.message)}</p></div></div>`;return}allRows=data||[];applyClientFilters()}
function setSpec(k){current=k in specs?k:'ALL';document.querySelectorAll('[data-spec]').forEach(x=>x.classList.toggle('active',x.dataset.spec===current));$('specialtySelect').value=current;load();document.querySelector('#masters')?.scrollIntoView({behavior:'smooth',block:'start'})}
renderSpecialties();refreshGeoSelect();$('searchIcon').innerHTML=icons.search;$('specialtyGrid').onclick=e=>{const b=e.target.closest('[data-spec]');if(b)setSpec(b.dataset.spec)};$('specialtySelect').onchange=()=>setSpec($('specialtySelect').value);$('searchForm').onsubmit=e=>{e.preventDefault();load();document.querySelector('#masters')?.scrollIntoView({behavior:'smooth',block:'start'})};let timer;$('q').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,280)};$('city').onchange=()=>{if($('city').value==='__choose__'){window.CUIM_GEO?.open?.();$('city').value=''}};$('sort').onchange=applyClientFilters;$('maxPrice').oninput=()=>{clearTimeout(timer);timer=setTimeout(applyClientFilters,180)};$('minRating').onchange=applyClientFilters;$('resetFilters').onclick=()=>{$('maxPrice').value='';$('minRating').value='0';$('sort').value='rating';setSpec('ALL')};$('mobileFilter').onclick=()=>{$('filterCard').classList.toggle('open')};window.addEventListener('cuim:geo-change',e=>{geoContext=e.detail||null;refreshGeoSelect();load()});load();