import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
const s=createClient('https://qgakliolffnwkymoqvzn.supabase.co','sb_publishable_WbZxATu_lxqWF21jR_qFag_fcEeVIMu');
let button=null,busy=false;
function decodeKey(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function profileReady(){const{data:{session}}=await s.auth.getSession();if(!session)return false;const{data,error}=await s.rpc('courier_my_profile');return !error&&!!data}
async function reg(){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Этот браузер не поддерживает Push-уведомления.');return navigator.serviceWorker.register('/sw.js',{scope:'/'})}
async function current(){const r=await reg();return r.pushManager.getSubscription()}
async function save(sub){const j=sub.toJSON(),keys=j.keys||{};const{error}=await s.rpc('courier_save_push_subscription',{p_endpoint:j.endpoint,p_p256dh:keys.p256dh,p_auth:keys.auth});if(error)throw error}
async function refresh(){if(!button)return;try{const sub=await current();const on=Notification.permission==='granted'&&!!sub;button.textContent=on?'🔔 Push включён':'🔔 Уведомления';button.dataset.on=on?'1':'0';button.title=on?'Фоновые уведомления о новых доставках включены':'Получать новые доставки даже при закрытой вкладке';if(on)await save(sub)}catch{button.textContent='🔔 Уведомления'}}
async function toggle(){if(busy)return;busy=true;button.disabled=true;try{const r=await reg(),old=await r.pushManager.getSubscription();if(old&&Notification.permission==='granted'){if(!confirm('Отключить фоновые уведомления о новых доставках?'))return;try{await s.rpc('courier_disable_push_subscription',{p_endpoint:old.endpoint})}catch{}await old.unsubscribe();await refresh();return}const perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('Разрешение на уведомления не предоставлено.');const{data:key,error}=await s.rpc('marketplace_push_public_key');if(error||!key)throw new Error('Не удалось получить ключ уведомлений.');const sub=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(key)});await save(sub);await refresh()}catch(e){alert(e?.message||String(e))}finally{busy=false;if(button)button.disabled=false}}
async function install(){if(button||!await profileReady())return false;const actions=document.querySelector('.top-actions');if(!actions)return false;button=document.createElement('button');button.type='button';button.className='btn light';button.id='courierPushButton';button.textContent='🔔 Уведомления';button.onclick=toggle;actions.prepend(button);await refresh();return true}
let tries=0;const timer=setInterval(async()=>{tries++;if(await install()||tries>120)clearInterval(timer)},150);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&button)refresh()});