import'./geo-core.js';
import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
const s=createClient('https://qgakliolffnwkymoqvzn.supabase.co','sb_publishable_WbZxATu_lxqWF21jR_qFag_fcEeVIMu');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sectionOrder=['goods','services','jobs','food','auto','ads','events'];
const svg=body=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const uiIcons={
 home:svg('<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9Z"/>'),
 catalog:svg('<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>'),
 beauty:svg('<path d="M12 3c3 4 5 6.6 5 10a5 5 0 0 1-10 0c0-3.4 2-6 5-10Z"/><path d="M9.5 14.5c.6 1.2 1.4 1.8 2.5 2"/>'),
 ads:svg('<path d="M4 6h16v12H4z"/><path d="M8 18v3m8-3v3M7 10h6m-6 4h10"/>'),
 account:svg('<circle cx="12" cy="8" r="4"/><path d="M5 21c.8-4 3.1-6 7-6s6.2 2 7 6"/>'),
 cart:svg('<path d="M3 4h2l2 11h10l3-8H6"/><circle cx="9" cy="20" r="1"/><circle cx="17" cy="20" r="1"/>'),
 message:svg('<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>'),
 pin:svg('<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.6"/>'),
 settings:svg('<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.86 2.86-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.4v-.1A1.7 1.7 0 0 0 8 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.86-2.86.06-.06A1.7 1.7 0 0 0 3.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H2V9.4h.1A1.7 1.7 0 0 0 3.6 8a1.7 1.7 0 0 0-.34-1.88l-.06-.06L6.06 3.2l.06.06A1.7 1.7 0 0 0 8 3.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V2h4.2v.1A1.7 1.7 0 0 0 15 3.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.86 2.86-.06.06A1.7 1.7 0 0 0 19.4 8c.14.4.36.75.66 1 .3.25.68.39 1.08.4H21v4.2h-.1A1.7 1.7 0 0 0 19.4 15Z"/>')
};

function geoContext(){return window.CUIM_GEO?.get?.()||null}
function geoLabel(c=geoContext()){
 if(!c)return'Москва · вся Москва';
 if(c.metro_name)return`м. ${c.metro_name} · ${Math.round(Number(c.radius_m||3000)/1000)} км`;
 if(c.area_name)return`${c.city_name||'Москва'} · ${c.area_short_name||c.area_name}`;
 return`${c.city_name||'Москва'} · вся Москва`;
}
function openGeo(e){e?.preventDefault?.();e?.stopPropagation?.();window.CUIM_GEO?.open?.()}

function installSearchSettings(){
 const bar=document.querySelector('.searchbar'),q=document.getElementById('q'),category=document.getElementById('category'),seller=document.getElementById('sellerFilter'),search=document.getElementById('searchBtn');
 if(!bar||!q||!category||!seller||!search||bar.dataset.geoSearch==='1')return;
 bar.dataset.geoSearch='1';bar.classList.add('cuim-search-enhanced');
 const geoBtn=document.createElement('button');geoBtn.type='button';geoBtn.id='searchGeoButton';geoBtn.className='search-geo-btn';geoBtn.innerHTML=`${uiIcons.pin}<span><b>Локация</b><small id="searchGeoLabel">${esc(geoLabel())}</small></span>`;geoBtn.onclick=openGeo;bar.insertBefore(geoBtn,search);
 const wrap=bar.closest('.search-wrap')||bar.parentElement;
 const toggle=document.createElement('button');toggle.type='button';toggle.className='search-settings-toggle';toggle.innerHTML=`${uiIcons.settings}<span>Настройки поиска</span><small id="searchSettingsSummary">${esc(geoLabel())}</small>`;bar.insertAdjacentElement('afterend',toggle);
 const panel=document.createElement('section');panel.className='search-settings-panel';panel.innerHTML=`<div class="search-settings-head"><div><b>Настройки поиска</b><span>Уточните категорию, компанию и место поиска</span></div><button type="button" class="search-settings-close" aria-label="Закрыть">×</button></div><div class="search-settings-grid"><label><span>Категория</span><select id="mobileSearchCategory"></select></label><label><span>Компания</span><select id="mobileSearchSeller"></select></label><div class="search-settings-location"><span>Локация</span><button type="button" id="mobileSearchGeo">${uiIcons.pin}<span><b id="mobileSearchGeoTitle">${esc(geoLabel())}</b><small>Округ, район, метро и радиус</small></span><strong>Изменить</strong></button></div></div><button type="button" class="search-settings-apply">Применить и искать</button>`;
 toggle.insertAdjacentElement('afterend',panel);
 const mc=panel.querySelector('#mobileSearchCategory'),ms=panel.querySelector('#mobileSearchSeller');
 const syncSelect=(src,dst)=>{const wanted=src.value;dst.innerHTML=src.innerHTML;dst.value=wanted};
 syncSelect(category,mc);syncSelect(seller,ms);
 const watch=(src,dst)=>new MutationObserver(()=>syncSelect(src,dst)).observe(src,{childList:true,subtree:true});watch(category,mc);watch(seller,ms);
 mc.onchange=()=>{category.value=mc.value;category.dispatchEvent(new Event('change',{bubbles:true}))};
 ms.onchange=()=>{seller.value=ms.value;seller.dispatchEvent(new Event('change',{bubbles:true}))};
 panel.querySelector('#mobileSearchGeo').onclick=openGeo;
 const close=()=>panel.classList.remove('open');toggle.onclick=()=>panel.classList.toggle('open');panel.querySelector('.search-settings-close').onclick=close;
 panel.querySelector('.search-settings-apply').onclick=()=>{category.value=mc.value;seller.value=ms.value;category.dispatchEvent(new Event('change',{bubbles:true}));seller.dispatchEvent(new Event('change',{bubbles:true}));search.click();close()};
 const update=()=>{const label=geoLabel();const a=document.getElementById('searchGeoLabel'),b=document.getElementById('searchSettingsSummary'),c=document.getElementById('mobileSearchGeoTitle');if(a)a.textContent=label;if(b)b.textContent=label;if(c)c.textContent=label};
 window.addEventListener('cuim:geo-change',update);window.CUIM_GEO?.ready?.then(update).catch(()=>{});update();
}

function installHomeUx(){
 const citySections=document.getElementById('citySections'),topin=document.querySelector('.topin');if(!citySections||!topin)return;
 document.body.classList.add('home-mobile-v3');
 if(!document.querySelector('link[data-home-mobile]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/homepage-mobile.css';l.dataset.homeMobile='1';document.head.appendChild(l)}
 const q=document.getElementById('q');if(q)q.placeholder='Что ищете в Москве?';
 const cityButton=document.getElementById('cityButton');if(cityButton){cityButton.onclick=openGeo;const c=geoContext();if(!c?.city_name)cityButton.textContent='📍 Москва'}
 installSearchSettings();
 if(!document.querySelector('.mobile-head-actions')){const a=document.createElement('div');a.className='mobile-head-actions';a.innerHTML=`<a class="mobile-head-action" href="/messages.html" aria-label="Сообщения">${uiIcons.message}</a><a class="mobile-head-action" href="/cart.html" aria-label="Корзина">${uiIcons.cart}<span class="mobile-cart-badge" id="mobileCartBadge"></span></a><a class="mobile-head-action" id="mobileAccountHead" href="/login.html" aria-label="Кабинет">${uiIcons.account}</a>`;topin.appendChild(a)}
 if(!document.querySelector('.home-beauty')){const beauty=document.createElement('section');beauty.className='home-beauty';beauty.innerHTML=`<div class="home-beauty-inner"><div><div class="home-beauty-kicker">Красота и онлайн-запись</div><h2>Мастера красоты рядом — запись на свободное время</h2><p>Ногти, волосы, брови, ресницы, косметология, массаж и другие специалисты. Сравнивайте услуги, портфолио и отзывы и записывайтесь прямо через ЦУИМ.</p><div class="home-beauty-actions"><a class="btn beauty-primary" href="/catalog/services/beauty/">Найти мастера</a><a class="btn beauty-secondary" href="/beauty-bookings.html">Мои записи</a><a class="btn beauty-secondary" href="/beauty-calendar.html">Beauty Pro</a></div><div class="home-beauty-features"><div class="home-beauty-feature"><b>Свободные окна</b><span>По реальному графику специалиста</span></div><div class="home-beauty-feature"><b>Отзывы клиентов</b><span>После завершённых визитов</span></div><div class="home-beauty-feature"><b>Запись онлайн</b><span>Без звонков и долгой переписки</span></div></div></div><div class="home-beauty-preview"><div class="beauty-preview-head"><div class="beauty-preview-avatar">${uiIcons.account}</div><div class="beauty-preview-copy"><b>Выберите мастера</b><span>Услуга · дата · свободное время</span></div></div><div class="beauty-preview-service"><b>Онлайн-запись в ЦУИМ</b><span>Свободные интервалы рассчитываются автоматически.</span></div><div class="beauty-preview-times"><span>10:00</span><span>11:30</span><span>14:00</span></div></div></div>`;citySections.insertAdjacentElement('afterend',beauty)}
 if(!document.querySelector('.mobile-bottom-nav')){const nav=document.createElement('nav');nav.className='mobile-bottom-nav';nav.setAttribute('aria-label','Мобильная навигация');nav.innerHTML=`<a class="active" href="/">${uiIcons.home}<span>Главная</span></a><a href="/catalog/">${uiIcons.catalog}<span>Каталог</span></a><a class="beauty-tab" href="/catalog/services/beauty/">${uiIcons.beauty}<span>Красота</span></a><a href="/catalog/ads/">${uiIcons.ads}<span>Объявления</span></a><a id="mobileAccountBottom" href="/login.html">${uiIcons.account}<span>Кабинет</span></a>`;document.body.appendChild(nav)}
 const updateCart=()=>{let count=0;try{const a=JSON.parse(localStorage.getItem('cuim-cart:v1')||'[]');count=Array.isArray(a)?a.reduce((n,x)=>n+Math.max(1,Number(x.quantity)||1),0):0}catch{}const b=document.getElementById('mobileCartBadge');if(b){b.textContent=count>99?'99+':String(count);b.classList.toggle('show',count>0)}};updateCart();window.addEventListener('storage',e=>{if(e.key==='cuim-cart:v1')updateCart()});document.addEventListener('click',e=>{if(e.target.closest('[data-cart]'))setTimeout(updateCart,50)});
 s.auth.getSession().then(({data})=>{const logged=!!data.session;for(const id of['mobileAccountHead','mobileAccountBottom']){const a=document.getElementById(id);if(a)a.href=logged?'/account.html':'/login.html'}}).catch(()=>{});
}
installHomeUx();

const style=document.createElement('style');style.textContent=`
.nav-catalog{position:relative;display:flex;align-items:center}.nav-catalog-trigger{border:0;background:transparent;color:#334155;font:inherit;font-weight:800;padding:10px 11px;border-radius:11px;cursor:pointer;display:flex;align-items:center;gap:6px}.nav-catalog-trigger:hover,.nav-catalog.open .nav-catalog-trigger{background:#f1f5f9;color:#2563eb}.nav-catalog-trigger .chev{font-size:11px;transition:.18s}.nav-catalog.open .nav-catalog-trigger .chev{transform:rotate(180deg)}.nav-mega{position:absolute;top:calc(100% + 13px);left:0;width:min(1040px,calc(100vw - 48px));background:#fff;border:1px solid #e2e8f0;border-radius:22px;box-shadow:0 26px 70px #0f172a26;padding:18px;display:none;z-index:80}.nav-catalog.open .nav-mega{display:block}.nav-mega:before{content:"";position:absolute;top:-8px;left:31px;width:15px;height:15px;background:#fff;border-left:1px solid #e2e8f0;border-top:1px solid #e2e8f0;transform:rotate(45deg)}.nav-mega-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:2px 4px 14px;border-bottom:1px solid #eef2f7;margin-bottom:14px}.nav-mega-head b{font-size:16px;color:#0f172a}.nav-mega-head a{font-size:12px;color:#2563eb;text-decoration:none;font-weight:800}.nav-mega-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.nav-mega-group{min-width:0;border-radius:16px;padding:12px;background:#f8fafc;border:1px solid #eef2f7}.nav-mega-title{padding:0 0 9px;color:#0f172a;text-decoration:none;font-weight:900;font-size:13px;display:flex;align-items:center;justify-content:space-between;gap:8px}.nav-mega-title:hover{color:#2563eb}.nav-mega-list{display:grid;gap:2px}.nav-mega-sub{color:#64748b;text-decoration:none;padding:6px 7px;border-radius:8px;font-size:12px;line-height:1.3}.nav-mega-sub:hover{background:#fff;color:#2563eb;box-shadow:0 1px 4px #0f172a0b}.nav-mega-empty{padding:20px;color:#64748b;font-size:13px}
.home-mobile-v3 .searchbar.cuim-search-enhanced{grid-template-columns:minmax(250px,1fr) 190px 170px minmax(185px,220px) auto}.search-geo-btn{border:1px solid #e2e8f0;background:#fff;color:#0f172a;border-radius:11px;padding:7px 11px;display:flex;align-items:center;gap:8px;min-width:0;cursor:pointer;text-align:left}.search-geo-btn:hover{border-color:#a5b4fc;background:#f8faff}.search-geo-btn>svg{width:19px;height:19px;color:#2563eb;flex:0 0 auto}.search-geo-btn>span{display:grid;min-width:0}.search-geo-btn b{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#64748b}.search-geo-btn small{font-size:12px;font-weight:800;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.search-settings-toggle,.search-settings-panel{display:none}
@media(max-width:1120px){.nav-mega-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.nav-mega{left:-80px}.home-mobile-v3 .searchbar.cuim-search-enhanced{grid-template-columns:minmax(220px,1fr) 170px 155px minmax(165px,190px) auto}}
@media(max-width:820px){.nav-catalog{display:none!important}.home-mobile-v3 .searchbar.cuim-search-enhanced{grid-template-columns:minmax(0,1fr) auto}.home-mobile-v3 .searchbar.cuim-search-enhanced select,.home-mobile-v3 .searchbar.cuim-search-enhanced .search-geo-btn{display:none!important}.search-settings-toggle{width:100%;margin-top:8px;border:1px solid #dbe3ef;background:#fff;border-radius:14px;padding:10px 12px;display:grid;grid-template-columns:20px 1fr auto;align-items:center;gap:8px;text-align:left;color:#334155;cursor:pointer}.search-settings-toggle>svg{width:19px;height:19px;color:#4f46e5}.search-settings-toggle>span{font-weight:850;font-size:12px}.search-settings-toggle>small{font-size:10px;color:#64748b;max-width:42vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.search-settings-panel{display:none;margin-top:8px;padding:14px;background:#fff;border:1px solid #dbe3ef;border-radius:18px;box-shadow:0 14px 34px #0f172a12}.search-settings-panel.open{display:block}.search-settings-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}.search-settings-head>div{display:grid;gap:3px}.search-settings-head b{font-size:15px}.search-settings-head span{font-size:11px;color:#64748b}.search-settings-close{width:32px;height:32px;border:1px solid #e2e8f0;background:#fff;border-radius:10px;font-size:21px;line-height:1;cursor:pointer}.search-settings-grid{display:grid;gap:10px}.search-settings-grid label,.search-settings-location{display:grid;gap:5px}.search-settings-grid label>span,.search-settings-location>span{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#64748b;font-weight:900}.search-settings-grid select{width:100%;padding:11px 12px;border:1px solid #dbe3ef;border-radius:12px;background:#fff;color:#0f172a}.search-settings-location>button{width:100%;border:1px solid #dbe3ef;background:#f8fafc;border-radius:13px;padding:10px;display:grid;grid-template-columns:20px 1fr auto;align-items:center;gap:9px;text-align:left;cursor:pointer}.search-settings-location>button>svg{width:19px;height:19px;color:#2563eb}.search-settings-location>button>span{display:grid;min-width:0}.search-settings-location>button b{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.search-settings-location>button small{font-size:10px;color:#64748b;margin-top:2px}.search-settings-location>button strong{font-size:10px;color:#2563eb}.search-settings-apply{margin-top:12px;width:100%;border:0;border-radius:12px;padding:11px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:900;cursor:pointer}}
`;document.head.appendChild(style);

async function init(){
 const nav=document.querySelector('.nav');if(!nav)return;
 const existing=[...nav.querySelectorAll('a')].find(a=>a.getAttribute('href')==='#citySections');if(!existing)return;
 const catalogLink=[...nav.querySelectorAll('a')].find(a=>a.getAttribute('href')==='#catalog');if(catalogLink)catalogLink.href='/catalog/';
 const host=document.createElement('div');host.className='nav-catalog';host.innerHTML=`<button class="nav-catalog-trigger" type="button" aria-expanded="false">Разделы <span class="chev">⌄</span></button><div class="nav-mega"><div class="nav-mega-head"><b>Категории и подкатегории</b><a href="/catalog/">Весь каталог →</a></div><div class="nav-mega-grid"><div class="nav-mega-empty">Загрузка…</div></div></div>`;existing.replaceWith(host);
 const trigger=host.querySelector('.nav-catalog-trigger'),mega=host.querySelector('.nav-mega'),grid=host.querySelector('.nav-mega-grid');
 const close=()=>{host.classList.remove('open');trigger.setAttribute('aria-expanded','false')},toggle=()=>{const open=!host.classList.contains('open');host.classList.toggle('open',open);trigger.setAttribute('aria-expanded',String(open))};
 trigger.onclick=e=>{e.stopPropagation();toggle()};mega.onclick=e=>e.stopPropagation();document.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});host.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover)').matches){host.classList.add('open');trigger.setAttribute('aria-expanded','true')}});host.addEventListener('mouseleave',()=>{if(matchMedia('(hover:hover)').matches)close()});
 const[{data:sections,error:se},{data:subs,error:su}]=await Promise.all([s.from('marketplace_city_sections').select('section_key,slug,title,sort_order').eq('active',true).order('sort_order'),s.from('marketplace_city_subcategories').select('section_key,subcategory_key,slug,title,sort_order').eq('active',true).order('sort_order')]);
 if(se||su){grid.innerHTML='<div class="nav-mega-empty">Не удалось загрузить разделы.</div>';return}
 const sectionMap=new Map((sections||[]).map(x=>[x.section_key,x])),subMap=new Map((subs||[]).map(x=>[x.subcategory_key,x]));
 const route=(section,sub='')=>{if(section==='all')return'/catalog/';const sec=sectionMap.get(section),sSlug=sec?.slug||section;if(!sub)return`/catalog/${encodeURIComponent(sSlug)}/`;const sb=subMap.get(sub);return`/catalog/${encodeURIComponent(sSlug)}/${encodeURIComponent(sb?.slug||sub)}/`};
 const groups=sectionOrder.filter(k=>sectionMap.has(k)).map(k=>({section:sectionMap.get(k),items:(subs||[]).filter(x=>x.section_key===k)}));
 grid.innerHTML=groups.map(g=>`<section class="nav-mega-group"><a class="nav-mega-title" href="${route(g.section.section_key)}"><span>${esc(g.section.title)}</span><span>→</span></a><div class="nav-mega-list">${g.items.map(x=>`<a class="nav-mega-sub" href="${route(x.section_key,x.subcategory_key)}">${esc(x.title)}</a>`).join('')}</div></section>`).join('');
 document.querySelectorAll('.city-section[data-section]').forEach(b=>{const key=b.dataset.section;b.onclick=()=>{location.href=route(key)}});document.querySelectorAll('[data-footer-section]').forEach(a=>{const key=a.dataset.footerSection;a.onclick=e=>{e.preventDefault();location.href=route(key)}});
}
init();