import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
const s=createClient('https://qgakliolffnwkymoqvzn.supabase.co','sb_publishable_WbZxATu_lxqWF21jR_qFag_fcEeVIMu');
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m])),money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v||0));
const order=['goods','services','jobs','food','auto','ads','events'];
const params=new URLSearchParams(location.search);let currentSection=params.get('section')||'all',currentSub=params.get('sub')||'';
let sections=[],subs=[],all=[],shown=[];
const sectionCopy={all:['Все категории','Товары, услуги и предложения компаний и специалистов города в одном месте.'],goods:['Товары','Магазины, локальные продавцы и городские товары.'],services:['Услуги','Компании, мастера и специалисты для личных и деловых задач.'],jobs:['Работа','Вакансии, подработка, удалённая и проектная работа.'],food:['Еда','Кафе, рестораны, доставка и продукты в городе.'],auto:['Авто','Сервисы, запчасти и предложения для автомобилистов.'],ads:['Объявления','Частные и коммерческие предложения жителей города.'],events:['Афиша','Концерты, события, выставки и городские мероприятия.']};
function route(section,sub=''){return`/catalog/?section=${encodeURIComponent(section)}${sub?`&sub=${encodeURIComponent(sub)}`:''}`}
function text(x){return[x.title,x.category,x.description,x.partner_name].filter(Boolean).join(' ').toLowerCase()}
function activeSub(){return subs.find(x=>x.subcategory_key===currentSub&&x.section_key===currentSection)||null}
function activeSection(){return sections.find(x=>x.section_key===currentSection)||null}
function sectionSubs(k){return subs.filter(x=>x.section_key===k)}
function matchesKeywords(x,words){const t=text(x);return(words||[]).some(w=>t.includes(String(w).toLowerCase()))}
function matchesSection(x,key){if(key==='all')return true;const words=sectionSubs(key).flatMap(v=>v.keywords||[]);return matchesKeywords(x,words)}
function setMeta(){const sec=activeSection(),sub=activeSub();const title=sub?.title||sec?.title||sectionCopy[currentSection]?.[0]||'Каталог';const desc=sub?`Предложения в подкатегории «${sub.title}» в городском маркетплейсе ЦУИМ.`:(sectionCopy[currentSection]?.[1]||sectionCopy.all[1]);document.title=`${title} — ЦУИМ`;document.querySelector('meta[name="description"]')?.setAttribute('content',desc);$('pageTitle').textContent=title;$('pageDescription').textContent=desc;$('heroEyebrow').textContent=sub?`${sec?.title||'Каталог'} · подкатегория`:currentSection==='all'?'Городской каталог':sec?.subtitle||'Городской раздел';$('contentTitle').textContent=sub?sub.title:(currentSection==='all'?'Все предложения':sec?.title||'Предложения');$('contentSubtitle').textContent=sub?'Товары, услуги и предложения, подходящие под эту подкатегорию.':(sectionCopy[currentSection]?.[1]||'Актуальные предложения Marketplace.');$('mobileCurrent').textContent=sub?.title||sec?.title||'Все категории';const ico=sec?.icon_url?`<img src="${esc(sec.icon_url)}" alt="${esc(title)}">`:esc(sec?.icon_fallback||'⌂');$('heroIcon').innerHTML=ico;const bc=[`<a href="/">Главная</a><span>›</span><a href="/catalog/">Каталог</a>`];if(sec)bc.push(`<span>›</span><a href="${route(sec.section_key)}">${esc(sec.title)}</a>`);if(sub)bc.push(`<span>›</span><span>${esc(sub.title)}</span>`);$('breadcrumbs').innerHTML=bc.join('')}
function renderNavigation(){$('sectionStrip').innerHTML=order.map(k=>{const x=sections.find(v=>v.section_key===k);if(!x)return'';return`<a class="section-pill ${currentSection===k?'active':''}" href="${route(k)}">${esc(x.title)}</a>`}).join('');$('sidebarContent').innerHTML=`<div class="side-section"><a class="side-title ${currentSection==='all'?'active':''}" href="/catalog/">Все категории <span>→</span></a></div>`+order.map(k=>{const x=sections.find(v=>v.section_key===k);if(!x)return'';const ss=sectionSubs(k);return`<div class="side-section"><a class="side-title ${currentSection===k&&!currentSub?'active':''}" href="${route(k)}">${esc(x.title)} <span>${ss.length}</span></a><div class="side-subs">${ss.map(v=>`<a class="side-sub ${currentSub===v.subcategory_key?'active':''}" href="${route(k,v.subcategory_key)}">${esc(v.title)}</a>`).join('')}</div></div>`}).join('')}
function apply(){const sub=activeSub(),q=$('search').value.trim().toLowerCase(),seller=$('sellerFilter').value,sort=$('sort').value;shown=all.filter(x=>matchesSection(x,currentSection));if(sub)shown=shown.filter(x=>matchesKeywords(x,sub.keywords));if(q)shown=shown.filter(x=>text(x).includes(q));if(seller)shown=shown.filter(x=>x.partner_id===seller);if(sort==='priceAsc')shown.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));else if(sort==='priceDesc')shown.sort((a,b)=>(b.price??-1)-(a.price??-1));else if(sort==='title')shown.sort((a,b)=>String(a.title).localeCompare(String(b.title),'ru'));renderResults()}
function card(x){return`<article class="product"><div class="product-img">${x.image_url?`<img src="${esc(x.image_url)}" loading="lazy" alt="${esc(x.title)}">`:'<span class="empty" style="padding:10px;border:0;background:transparent">Нет фото</span>'}<span class="badge">${esc(x.category||'Предложение')}</span></div><div class="product-body"><a class="seller" href="/seller.html?id=${encodeURIComponent(x.partner_id)}">${esc(x.partner_name||'Участник города')}</a><h3>${esc(x.title)}</h3><div class="price">${x.price==null?'Цена по запросу':money(x.price)}</div><div class="address">${esc([x.city,x.address].filter(Boolean).join(', ')||'Город не указан')}</div><div class="product-actions"><button class="primary" data-cart="${x.id}">В корзину</button><a class="secondary" href="/seller.html?id=${encodeURIComponent(x.partner_id)}">Компания</a></div></div></article>`}
function renderResults(){$('resultCount').textContent=`${shown.length} предложений`;$('offersMeta').textContent=`${shown.length} предложений`;const companiesMap=new Map;for(const x of shown){if(!x.partner_id)continue;if(!companiesMap.has(x.partner_id))companiesMap.set(x.partner_id,{id:x.partner_id,name:x.partner_name||'Участник города',city:x.city||'',count:0});companiesMap.get(x.partner_id).count++}const companies=[...companiesMap.values()];$('companiesMeta').textContent=`${companies.length} компаний и специалистов`;$('products').innerHTML=shown.length?shown.map(card).join(''):'<div class="empty"><b>В этой категории пока нет подходящих предложений.</b><br>Страница уже готова — новые товары и услуги появятся здесь автоматически.</div>';$('companies').innerHTML=companies.length?companies.slice(0,12).map(x=>`<a class="company" href="/seller.html?id=${encodeURIComponent(x.id)}"><div class="avatar">${esc(String(x.name).split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase())}</div><div><b>${esc(x.name)}</b><span>${x.count} предложений${x.city?` · ${esc(x.city)}`:''}</span></div></a>`).join(''):'<div class="empty">Компании появятся здесь вместе с предложениями.</div>';$('companiesBlock').style.display=companies.length?'block':'none';bindCart()}
function bindCart(){document.querySelectorAll('[data-cart]').forEach(b=>b.onclick=()=>{const key='cuim-cart:v1';let a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const f=a.find(v=>v.product_id===b.dataset.cart);f?f.quantity++:a.push({product_id:b.dataset.cart,quantity:1});localStorage.setItem(key,JSON.stringify(a));b.textContent='Добавлено ✓';setTimeout(()=>b.textContent='В корзину',1100)})}
function renderSellerFilter(){const g=new Map;for(const x of all.filter(v=>matchesSection(v,currentSection))){if(x.partner_id&&!g.has(x.partner_id))g.set(x.partner_id,x.partner_name||'Компания')}$('sellerFilter').innerHTML='<option value="">Все компании</option>'+[...g.entries()].sort((a,b)=>a[1].localeCompare(b[1],'ru')).map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('')}
async function load(){const[secR,subR,prodR]=await Promise.all([s.from('marketplace_city_sections').select('section_key,title,subtitle,icon_url,icon_fallback,sort_order').eq('active',true).order('sort_order'),s.from('marketplace_city_subcategories').select('section_key,subcategory_key,title,keywords,sort_order').eq('active',true).order('sort_order'),s.rpc('marketplace_products',{p_query:null,p_category:null,p_partner_id:null})]);if(secR.error||subR.error||prodR.error){$('products').innerHTML=`<div class="empty">Не удалось загрузить каталог.<br>${esc(secR.error?.message||subR.error?.message||prodR.error?.message||'')}</div>`;return}sections=(secR.data||[]).filter(x=>x.section_key!=='all');subs=subR.data||[];all=prodR.data||[];if(currentSection!=='all'&&!sections.some(x=>x.section_key===currentSection)){currentSection='all';currentSub=''}if(currentSub&&!subs.some(x=>x.subcategory_key===currentSub&&x.section_key===currentSection))currentSub='';setMeta();renderNavigation();renderSellerFilter();apply()}
$('search').oninput=apply;$('searchBtn').onclick=apply;$('sellerFilter').onchange=apply;$('sort').onchange=apply;$('search').onkeydown=e=>{if(e.key==='Enter')apply()};const openSide=()=>{$('catalogSidebar').classList.add('open');$('sidebarShade').classList.add('show')},closeSide=()=>{$('catalogSidebar').classList.remove('open');$('sidebarShade').classList.remove('show')};$('sidebarOpen').onclick=openSide;$('sidebarClose').onclick=closeSide;$('sidebarShade').onclick=closeSide;load();
